baseURL: https://elaborate-sprite-b67a31.netlify.app/
title: Hugo Bootstrap Skeleton
theme: github.com/razonyang/hugo-theme-bootstrap
copyright: 'Copyright © 2021-{year} Chris Munoz. All Rights Reserved.'
defaultContentLanguage: en
# hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10 # paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  category: categories
  # series: series
  tag: tags
  # authors: authors

build:
  writeStats: true

permalinks:
  news: /news/:year/:month/:title/

# module:
  # proxy: https://goproxy.cn

outputs:
  home:
    - HTML
    - RSS
    - JSON
    - Algolia
outputFormats:
  Algolia:
    baseName: algolia
    isPlainText: true
    mediaType: application/json
    notAlternative: true
params:
  algolia:
    vars:
      - title
      - summary
      - date
      - publishdate
      - expirydate
      - permalink
      - image
    params:
      - tags
        
