baseURL = "https://notes.munozpi.com"
title = "Munozpi a blog on all things tech"
# theme = "hugo-theme-bootstrap" # install via git submodule
theme = "github.com/razonyang/hugo-theme-bootstrap" # install via hugo module
copyright = "Copyright © {year} Chris Munoz. All Rights Reserved."

# Multilingual mode
defaultContentLanguage = "en"
# defaultContentLanguageInSubdir = true # If you use only one language comment this option
# disableLanguages = ["fr", "zh-cn" ,"zh-tw", "ar", "ja"] # Uncomment in order to disable one or more language

# Pagination
paginate = 10
# paginatePath = "page"

# Disqus
# disqusShortname = "yourdiscussshortname"

# Google analytics
# googleAnalytics = "UA-123-45"

enableRobotsTXT = true

enableEmoji = true

enableGitInfo = false

# hasCJKLanguage = true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.

pygmentsUseClasses = true

timeout = "120s"

[blackfriday]
  hrefTargetBlank = true

[outputs]
  home = ["HTML", "RSS", "JSON"]

[taxonomies]
  # category = "categories"
  # series = "series"
  tag = "tags"
  # author = "authors"

[build]
  writeStats = true
