main:
  - name: Home
    identifier: home
    url: https://cmpi4.com/
    weight: 1
    params:
      icon: '<i class="fas fa-fw fa-home"></i>'

  - name: Blog
    identifier: blog
    weight: 3
    params:
      icon: '<i class="fas fa-fw fa-blog text-warning"></i>'
      description: 'Blog Menu Description'





# main:
#   - identifier: home
#     name: Home
#     weight: 1
#     url: https://hbs.razonyang.com/
#     params:
#       icon: <i class="fas fa-home"></i>
#   - identifier: blog
#     name: Blog
#     weight: 3
#     params:
#       icon: <i class="fas fa-fw fa-blog"></i>
  # - name: Support
  #   identifier: support
  #   weight: 40
  #   params:
  #     description: The HBS Support Community
  #     icon: <i class="fas fa-fw fa-info-circle"></i>
  # - name: Repository
  #   identifier: repository
  #   parent: support
  #   url: https://github.com/razonyang/hugo-theme-bootstrap
  #   weight: 1
  #   params:
  #     icon: <i class="fab fa-fw fa-github text-primary"></i>
  # - name: Discussions
  #   identifier: discussions
  #   parent: support
  #   url: https://github.com/razonyang/hugo-theme-bootstrap/discussions/new
  #   weight: 2
  #   params:
  #     description: Ask and discuss questions with others.
  #     icon: <i class="fas fa-fw fa-comments text-success"></i>
  # - name: Features Request
  #   identifier: feature-request
  #   parent: support
  #   url: https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=feature_request.yml
  #   weight: 3
  #   params:
  #     description: Suggest new or updated features.
  #     icon: <i class="fas fa-fw fa-lightbulb text-warning"></i>
  # - name: Bug Report
  #   identifier: bug-report
  #   parent: support
  #   url: https://github.com/razonyang/hugo-theme-bootstrap/issues/new?template=bug_report.yml
  #   weight: 3
  #   params:
  #     description: Tell us about a bug or issue.
  #     icon: <i class="fas fa-fw fa-bug text-danger"></i>
  # - parent: support
  #   weight: 4
  #   params:
  #     divider: true
