name: Check for broken links

on:
  push:
    branches: 
      - main 

env:
  URL: https://munozpi.com
  CONFIG: hydra-config.json

jobs:
  check:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Check out main to get config file
        uses: actions/checkout@main
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
