name: Check for broken links

on:
  push:
    branches: 
      - main 

env:
  URL: https://munozpi.com
  CONFIG: hydra-config.json
  FILENAME: report.yaml

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out main to get config file
        uses: actions/checkout@main
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
