[build]
publish = "public"
command = "hugo --gc --minify"

[build.environment]
HUGO_VERSION = "0.147.7"
GO_VERSION = "1.24.3"
HUGO_ENABLEGITINFO = "true"

[context.production.environment]
HUGO_ENV = "production"

[[headers]]
for = "/*"
[headers.values]
Referrer-Policy = "strict-origin-when-cross-origin"
X-Content-Type-Options = "nosniff"
X-Frame-Options = "deny"
X-XSS-Protection = "1; mode=block"

[[redirects]]
from = "/:lang/*"
to = "/:lang/404.html"
status = 404

[[redirects]]
from = "/*"
to = "/en-us/404.html" # Replace the "en" to your default language code if "defaultContentLanguageInSubdir" is enabled, otherwise use "/404.html" instead.
status = 404
